# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"

  config.vm.box_check_update = false

  config.vm.synced_folder "C:/WORK_LOCAL/", "/opt/WORK_LOCAL"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
	 vb.cpus = 1
   end
  
  config.vm.provision "shell", inline: <<-SHELL
     yum update -y 
	 yum upgrade -y
   SHELL
end
