# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/groovy64"
  config.vm.box_check_update = false

  config.vm.synced_folder "C:/WORK_LOCAL/", "/opt/WORK_LOCAL"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "1024"
	 vb.cpus = 1
   end
  

  config.vm.provision "shell", path: ./ubu_min_installer.sh
end
